Repository Hrr-HabbitRoutineResult/Hrr_BE, pull requests merged in 2025-01, with the labels that each got.

#10 Feat: Add swagger annotations
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth.controller.js
  src/controllers/board.controller.js
  src/controllers/challenge.controller.js
  src/controllers/challenge/category.controller.js
  src/controllers/challenge/list.controller.js
  src/controllers/challenge/participation.controller.js
  src/controllers/message.controller.js
  src/controllers/post.controller.js
  src/controllers/users.controller.js
  src/controllers/verification/comment.controller.js
  src/controllers/verification/like.controller.js
  src/controllers/verification/scrap.controller.js
  src/controllers/verification/verification.controller.js
  src/index.js
  src/routes/auth.routes.js
  src/routes/board.routes.js
  src/routes/challenge.routes.js
  src/routes/message.routes.js
  src/routes/post.routes.js
  src/routes/users.routes.js
  src/routes/verification.routes.js
Labels: :sparkles: Feat

#13 Feat/#8 set database
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.js
  src/db.config.js
Labels: :sparkles: Feat

#14 [Pre-work] DB, Swagger 세팅 완료
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.js
  src/app.js
  src/controllers/auth.controller.js
  src/controllers/board.controller.js
  src/controllers/challenge.controller.js
  src/controllers/challenge/category.controller.js
  src/controllers/challenge/list.controller.js
  src/controllers/challenge/participation.controller.js
  src/controllers/message.controller.js
  src/controllers/post.controller.js
  src/controllers/users.controller.js
  src/controllers/verification/comment.controller.js
  src/controllers/verification/like.controller.js
  src/controllers/verification/scrap.controller.js
  src/controllers/verification/verification.controller.js
  src/db.config.js
  src/index.js
  src/routes/auth.routes.js
  src/routes/board.routes.js
  src/routes/challenge.routes.js
  src/routes/message.routes.js
  src/routes/post.routes.js
  src/routes/users.routes.js
  src/routes/verification.routes.js
Labels: :basecamp:Pre-work

#11 Feat/#7-kakao-login-api
  controllers/userController.js
  models/userDao.js
  package-lock.json
  package.json
  routers/index.js
  routers/userRouters.js
  services/userService.js
Labels: :sparkles: Feat

#16 Feat:/#15- modify-database Fix
  prisma/schema.prisma
  prisma/seed.js
  prisma/seed.sql
Labels: :bug: Bug

#19 Feat: modify-database-update prisma files
  prisma/migrations/20250113120101_hrr_db_20250113/migration.sql
  prisma/migrations/20250114132920_v2/migration.sql
  prisma/migrations/20250115081846_v3/migration.sql
  prisma/migrations/20250115083611_v4/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
Labels: :bug: Bug

#21 [Feat] Prisma migration 내용 develop branch에 적용
  README.md
  prisma/migrations/20250113120101_hrr_db_20250113/migration.sql
  prisma/migrations/20250114132920_v2/migration.sql
  prisma/migrations/20250115081846_v3/migration.sql
  prisma/migrations/20250115083611_v4/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  prisma/seed.sql
  src/app.js
  src/controllers/auth.controller.js
  src/controllers/board.controller.js
  src/controllers/challenge.controller.js
  src/controllers/challenge/list.controller.js
  src/controllers/challenge/participation.controller.js
  src/controllers/message.controller.js
  src/controllers/post.controller.js
  src/controllers/users.controller.js
  src/controllers/verification/comment.controller.js
  src/controllers/verification/like.controller.js
  src/controllers/verification/scrap.controller.js
  src/controllers/verification/verification.controller.js
Labels: :sparkles: Feat

#23 Chore: Link test DB server
  prisma/migrations/20250116111044_localv1/migration.sql
  prisma/schema.prisma
  src/db.config.js
Labels: :broom: Chore

#30 Feat/#26 register api
  package-lock.json
  package.json
  prisma/migrations/20250119115052_localv2/migration.sql
  prisma/migrations/20250120023710_localv3/migration.sql
  prisma/schema.prisma
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/index.js
  src/repositories/auth.repository.js
  src/routes/auth.routes.js
  src/services/auth.service.js
  src/utils/cronjobs.util.js
  src/utils/sendmail.util.js
Labels: :sparkles: Feat

#31 Refactor: Fix json braces
  src/controllers/auth.controller.js
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :recycle: Refactor

#33 Feat/#27 create Challenge api
  package-lock.json
  package.json
  prisma/migrations/20250120065915_/migration.sql
  prisma/migrations/20250120102557_/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  src/controllers/challenge/list.controller.js
  src/dtos/challenge/list.dto.js
  src/errors/challenge/list.error.js
  src/repositories/challenge/list.repository.js
  src/services/challenge/list.service.js
Labels: :sparkles: Feat

#37 Feat/#36 get board list api
  models/userDao.js
  prisma/migrations/20250121054847_/migration.sql
  prisma/migrations/20250121063910_/migration.sql
  prisma/schema.prisma
  routers/index.js
  routers/userRouters.js
  src/controllers/board.controller.js
  src/dtos/board.dto.js
  src/repositories/auth.repository.js
  src/repositories/board.repository.js
  src/routes/board.routes.js
  src/services/board.service.js
Labels: :sparkles: Feat

#39 Feat: Add board pin, unpin api
  src/controllers/board.controller.js
  src/controllers/challenge/list.controller.js
  src/dtos/challenge/list.dto.js
  src/errors/board.error.js
  src/repositories/board.repository.js
  src/repositories/challenge/list.repository.js
  src/routes/board.routes.js
  src/services/auth.service.js
  src/services/board.service.js
  src/utils/cronjobs.util.js
  src/utils/sendmail.util.js
Labels: :sparkles: Feat

#42 Feat/#24 user info api
  controllers/userController.js
  src/controllers/users.controller.js
  src/dtos/challenge/list.dto.js
  src/dtos/user.dto.js
  src/errors/users.error.js
  src/repositories/badge.repository.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/auth.service.js
  src/services/userService.js
  src/services/users.service.js
Labels: :sparkles: Feat

#41 Feat: Add Create Board API
  prisma/migrations/20250121100106_/migration.sql
  prisma/schema.prisma
  src/controllers/board.controller.js
  src/dtos/board.dto.js
  src/repositories/board.repository.js
  src/routes/board.routes.js
  src/services/board.service.js
Labels: :sparkles: Feat

#45 Feat: Add get challenge detail API
  prisma/migrations/20250121163633_/migration.sql
  src/controllers/challenge/list.controller.js
  src/errors/challenge/list.error.js
  src/repositories/challenge/list.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/list.service.js
Labels: :sparkles: Feat

#53 Fix: Token server error
  src/middlewares/auth.middleware.js
Labels: :bug: Bug

#49 Feat/#34 user-challenge-ongoing
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/errors/users.error.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#56 Fix: Database change
  prisma/migrations/20250126151715_/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  prisma/seed.sql
Labels: :bug: Bug

#57 Feat/#43 join challenge api
  prisma/schema.prisma
  src/controllers/auth.controller.js
  src/controllers/challenge/participation.controller.js
  src/dtos/challenge/participation.dto.js
  src/errors/challenge/participation.error.js
  src/repositories/challenge/participation.repository.js
  src/routes/challenge.routes.js
  src/services/auth.service.js
  src/services/challenge/participation.service.js
Labels: :sparkles: Feat

#59 최근 완주한 챌린지 API
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/errors/users.error.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#62 Fix: Add nickname in register logic
  prisma/migrations/20250128090033_/migration.sql
  prisma/schema.prisma
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :sparkles: Feat

#67 develop을 main에 병합 1/29
  package-lock.json
  package.json
  prisma/migrations/20250116111044_localv1/migration.sql
  prisma/migrations/20250119115052_localv2/migration.sql
  prisma/migrations/20250120023710_localv3/migration.sql
  prisma/migrations/20250120065915_/migration.sql
  prisma/migrations/20250120102557_/migration.sql
  prisma/migrations/20250121054847_/migration.sql
  prisma/migrations/20250121063910_/migration.sql
  prisma/migrations/20250121100106_/migration.sql
  prisma/migrations/20250121163633_/migration.sql
  prisma/migrations/20250126151715_/migration.sql
  prisma/migrations/20250126202711_/migration.sql
  prisma/migrations/20250128090033_/migration.sql
  prisma/prisma/seed.js
  prisma/schema.prisma
  prisma/seed.js
  prisma/seed.sql
  src/controllers/auth.controller.js
  src/controllers/board.controller.js
  src/controllers/challenge/list.controller.js
  src/controllers/challenge/participation.controller.js
  src/controllers/users.controller.js
  src/db.config.js
  src/dtos/auth.dto.js
  src/dtos/board.dto.js
  src/dtos/challenge/list.dto.js
  src/dtos/challenge/participation.dto.js
  src/dtos/user.dto.js
  src/errors/auth.error.js
  src/errors/board.error.js
  src/errors/challenge/list.error.js
  src/errors/challenge/participation.error.js
  src/errors/users.error.js
  src/index.js
  src/logger.js
  src/middlewares/auth.middleware.js
  src/repositories/auth.repository.js
  src/repositories/badge.repository.js
  src/repositories/board.repository.js
  src/repositories/challenge/list.repository.js
  src/repositories/challenge/participation.repository.js
  src/repositories/users.repository.js
  src/routes/auth.routes.js
  src/routes/board.routes.js
  src/routes/challenge.routes.js
  src/routes/users.routes.js
  src/services/auth.service.js
  src/services/board.service.js
  src/services/challenge/list.service.js
  src/services/challenge/participation.service.js
  src/services/users.service.js
  src/utils/cronjobs.util.js
  src/utils/sendmail.util.js
Labels: :broom: Chore

#68 Fix: fix deploy-main.yml npm run dev to npm start
  .github/workflows/deploy-main.yml
Labels: :bug: Bug

#66 Fix: Database change - Delete unnecessary column
  prisma/schema.prisma
Labels: :bug: Bug

#65 Feat: 사용자의 인증 기록 조회 API
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#72 Feat/#63 camera verification api
  prisma/migrations/20250129140729_/migration.sql
  prisma/migrations/20250129141838_/migration.sql
  prisma/migrations/20250130040940_/migration.sql
  prisma/schema.prisma
  src/app.js
  src/controllers/verification/verification.controller.js
  src/dtos/verification/verification.dto.js
  src/errors/database.error.js
  src/errors/verification/verification.error.js
  src/repositories/verification/verification.repository.js
  src/routes/verification.routes.js
  src/services/verification/verification.service.js
Labels: :sparkles: Feat

#74 Feat/#70 challenger list api
  prisma/migrations/20250130142445_/migration.sql
  prisma/schema.prisma
  src/controllers/challenge/participation.controller.js
  src/repositories/challenge/participation.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/participation.service.js
Labels: :sparkles: Feat

#73 Feat: 사용자 팔로우
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/errors/users.error.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#79 Feat: 사용자 언팔로우
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/errors/users.error.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#77 Feat/verification like api
  prisma/migrations/20250130154423_/migration.sql
  prisma/schema.prisma
  src/controllers/challenge/participation.controller.js
  src/controllers/verification/like.controller.js
  src/dtos/verification/like.dto.js
  src/dtos/verification/verification.dto.js
  src/errors/verification/like.error.js
  src/repositories/verification/like.repository.js
  src/routes/verification.routes.js
  src/services/verification/like.service.js
Labels: :sparkles: Feat

#83 Fix: Fix morganMiddleware & error logger
  src/app.js
  src/index.js
Labels: :bug: Bug

#85 Feat: 배지 조건 조회
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#90 Feat/#86 patch verification comment api
  src/controllers/verification/comment.controller.js
  src/errors/verification/comment.error.js
  src/repositories/verification/comment.repository.js
  src/routes/verification.routes.js
  src/services/verification/comment.service.js
Labels: :sparkles: Feat

#48 Feat: Get challenge category API & Bug: database seed file
  src/controllers/challenge/category.controller.js
  src/errors/challenge/category.error.js
  src/repositories/challenge/category.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/category.service.js
Labels: :sparkles: Feat

#95 Feat/#94 get scrap verification api
  src/controllers/users.controller.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#92 Feat/#91 challenge text verification
  src/controllers/verification/verification.controller.js
  src/dtos/verification/verification.dto.js
  src/repositories/verification/verification.repository.js
  src/routes/verification.routes.js
  src/services/verification/verification.service.js
Labels: :sparkles: Feat
