Repository Hrr-HabbitRoutineResult/Hrr_BE, pull requests merged in 2025-02, with the labels that each got.

#105 Fix/#104 swagger bug api
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth.controller.js
  src/controllers/board.controller.js
  src/controllers/challenge/category.controller.js
  src/controllers/challenge/list.controller.js
  src/controllers/challenge/participation.controller.js
  src/controllers/post.controller.js
  src/controllers/users.controller.js
  src/controllers/verification/comment.controller.js
  src/controllers/verification/like.controller.js
  src/controllers/verification/scrap.controller.js
  src/controllers/verification/verification.controller.js
  src/docs/swagger.json
  src/docs/swagger/auth.json
  src/docs/swagger/board.json
  src/docs/swagger/category.json
  src/docs/swagger/comment.json
  src/docs/swagger/like.json
  src/docs/swagger/list.json
  src/docs/swagger/participation.json
  src/docs/swagger/post.json
  src/docs/swagger/scrap.json
  src/docs/swagger/swaggerRoot.json
  src/docs/swagger/user.json
  src/docs/swagger/verification.json
  src/docs/swaggerMerge.js
  src/index.js
  src/routes/challenge.routes.js
Labels: :bug: Bug, :recycle: Refactor

#101 Feat: 레벨 화면 조회
  prisma/migrations/20250131182958_add_level_condition_and_user_level/migration.sql
  prisma/migrations/20250201091029_edit_type_to_enum/migration.sql
  prisma/schema.prisma
  src/controllers/users.controller.js
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#110 Feat/#100 get verification detail api
  src/controllers/verification/verification.controller.js
  src/docs/swagger.json
  src/docs/swagger/board.json
  src/docs/swagger/category.json
  src/docs/swagger/comment.json
  src/docs/swagger/like.json
  src/docs/swagger/list.json
  src/docs/swagger/participation.json
  src/docs/swagger/scrap.json
  src/docs/swagger/user.json
  src/docs/swagger/verification.json
  src/errors/verification/verification.error.js
  src/repositories/verification/verification.repository.js
  src/routes/verification.routes.js
  src/services/verification/verification.service.js
Labels: :sparkles: Feat

#103 Feat: 사용자의 챌린지 인증 현황
  src/controllers/challenge/participation.controller.js
  src/controllers/users.controller.js
  src/docs/swagger.json
  src/docs/swagger/participation.json
  src/docs/swagger/user.json
  src/dtos/challenge/participation.dto.js
  src/repositories/challenge/participation.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/participation.service.js
Labels: :sparkles: Feat

#111 Feat/#63 camera verification api
  src/docs/swagger.json
  src/docs/swagger/verification.json
  src/repositories/verification/verification.repository.js
Labels: :sparkles: Feat

#120 Refactor/#119 fix user api
  package-lock.json
  package.json
  src/controllers/users.controller.js
  src/docs/swagger.json
  src/docs/swagger/user.json
  src/dtos/user.dto.js
  src/repositories/auth.repository.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :recycle: Refactor

#116 Feat: 챌린지 인증 현황-챌린저
  prisma/migrations/20250206161630_/migration.sql
  prisma/schema.prisma
  src/controllers/verification/verification.controller.js
  src/docs/swagger.json
  src/docs/swagger/verification.json
  src/dtos/verification/verification.dto.js
  src/repositories/verification/verification.repository.js
  src/routes/verification.routes.js
  src/services/verification/verification.service.js
Labels: :sparkles: Feat

#118 Fix: join-challenge-api, add currentParticipants increase logic
  prisma/schema.prisma
  src/controllers/auth.controller.js
  src/docs/swagger.json
  src/docs/swagger/participation.json
  src/repositories/challenge/list.repository.js
  src/repositories/challenge/participation.repository.js
Labels: :bug: Bug

#124 Feat: get-Daily-hot-challenge
  prisma/migrations/20250201161829_20250202_add_current_and_datetime/migration.sql
  prisma/migrations/20250202093255_20250202_all_include_and_add_frequency_value/migration.sql
  prisma/migrations/20250204084927_20250204_null_change/migration.sql
  prisma/migrations/20250206161630_/migration.sql
  prisma/migrations/20250209122056_20250209_for_test/migration.sql
  prisma/schema.prisma
  src/controllers/challenge/category.controller.js
  src/db.config.js
  src/errors/challenge/category.error.js
  src/repositories/challenge/category.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/category.service.js
  src/utils/cronjobs.util.js
Labels: :sparkles: Feat

#127 Feat/#126 block user api
  prisma/migrations/20250212170633_/migration.sql
  prisma/schema.prisma
  src/controllers/challenge/participation.controller.js
  src/controllers/users.controller.js
  src/docs/swagger.json
  src/docs/swagger/user.json
  src/dtos/user.dto.js
  src/errors/users.error.js
  src/repositories/auth.repository.js
  src/repositories/users.repository.js
  src/routes/challenge.routes.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#132 Fix: following api error
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/services/users.service.js
Labels: :bug: Bug

#130 [Bug]모든 인증 기록 출력
  src/dtos/user.dto.js
Labels: :bug: Bug

#131 Feat: nickname-check api
  src/controllers/auth.controller.js
  src/docs/swagger.json
  src/docs/swagger/auth.json
  src/dtos/auth.dto.js
  src/repositories/auth.repository.js
  src/routes/auth.routes.js
  src/routes/users.routes.js
  src/services/auth.service.js
Labels: :sparkles: Feat

#135 Fix: get-daily-hot-challenge-Add freqencyValue and duration response
  src/services/challenge/category.service.js
Labels: :bug: Bug

#136 [Feat] 최근 획득한 배지 조회
  src/controllers/users.controller.js
  src/docs/swagger.json
  src/docs/swagger/user.json
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :sparkles: Feat

#46 Feat: Get challenge list api
  prisma/migrations/20250126171910_/migration.sql
  src/controllers/challenge/list.controller.js
  src/docs/swagger.json
  src/errors/challenge/list.error.js
  src/repositories/challenge/list.repository.js
  src/services/challenge/list.service.js
Labels: :sparkles: Feat

#139 Feat: change email-verification-logic
  prisma/migrations/20250214144337_/migration.sql
  prisma/schema.prisma
  src/controllers/users.controller.js
  src/docs/swagger.json
  src/docs/swagger/user.json
  src/errors/auth.error.js
  src/repositories/users.repository.js
  src/routes/auth.routes.js
  src/routes/users.routes.js
  src/services/auth.service.js
  src/services/users.service.js
Labels: :sparkles: Feat

#144 Feat: Add S3 upload logic!!!!
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/controllers/verification/verification.controller.js
  src/docs/swagger/verification.json
  src/dtos/verification/verification.dto.js
  src/middlewares/uploadMiddleware.js
  src/repositories/users.repository.js
  src/routes/verification.routes.js
  src/services/auth.service.js
  src/services/verification/verification.service.js
  src/utils/s3Uploader.js
Labels: :sparkles: Feat

#141 [Bug] 배지 별로 나눠서 조회
  src/controllers/users.controller.js
  src/docs/swagger/user.json
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: :bug: Bug

#147 Feat: Challenge scrap, like
  prisma/migrations/20250215143342_/migration.sql
  prisma/migrations/20250215144434_/migration.sql
  prisma/migrations/20250215144754_y/migration.sql
  prisma/schema.prisma
  src/controllers/challenge/like.controller.js
  src/controllers/challenge/scrap.controller.js
  src/docs/swagger/like.json
  src/docs/swagger/scrap.json
  src/dtos/challenge/like.dto.js
  src/dtos/challenge/scrap.dto.js
  src/errors/auth.error.js
  src/repositories/challenge/like.repository.js
  src/repositories/challenge/scrap.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/like.service.js
  src/services/challenge/scrap.service.js
Labels: :sparkles: Feat

#150 Fix: register response type
  src/docs/swagger/auth.json
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :sparkles: Feat

#152 Feat: fix swagger on following
  src/controllers/users.controller.js
  src/docs/swagger/user.json
  src/repositories/challenge/like.repository.js
  src/repositories/challenge/scrap.repository.js
  src/repositories/users.repository.js
Labels: :sparkles: Feat

#161 [bug] 배지 변경 수정
  src/controllers/users.controller.js
  src/docs/swagger/user.json
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/services/users.service.js
Labels: :bug: Bug

#158 [Bug] 카카오 로그인 response에 user_id 추가
  src/controllers/auth.controller.js
  src/docs/swagger/auth.json
  src/services/auth.service.js
Labels: :bug: Bug

#163 [bug] 카카오 로그인 시 id가 전달되지 않는 문제 해결
  src/repositories/users.repository.js
  src/services/auth.service.js
Labels: :bug: Bug

#165 [bug] 배지 조건 충족 시 자동으로 배지 획득
  src/docs/swagger/user.json
  src/dtos/user.dto.js
  src/repositories/users.repository.js
  src/services/users.service.js
Labels: :bug: Bug

#167 Fix: #166-create-challenge-api
  src/controllers/challenge/list.controller.js
  src/dtos/challenge/list.dto.js
  src/repositories/challenge/list.repository.js
  src/services/challenge/list.service.js
Labels: :bug: Bug

#173 Feat/#172 img upload api
  package-lock.json
  package.json
  src/app.js
  src/controllers/util.controller.js
  src/controllers/verification/verification.controller.js
  src/docs/swagger/util.json
  src/docs/swagger/verification.json
  src/routes/util.routes.js
  src/utils/s3Uploader.js
Labels: :sparkles: Feat

#176 Chore: add logger to unexpected problems
  src/repositories/auth.repository.js
  src/repositories/board.repository.js
  src/repositories/challenge/category.repository.js
  src/repositories/challenge/like.repository.js
  src/repositories/challenge/list.repository.js
  src/repositories/challenge/participation.repository.js
  src/repositories/challenge/scrap.repository.js
  src/repositories/users.repository.js
  src/repositories/verification/comment.repository.js
  src/repositories/verification/like.repository.js
  src/repositories/verification/scrap.repository.js
  src/repositories/verification/verification.repository.js
Labels: :broom: Chore

#178 [Bug] 최근 획득 배지 user_badge 없을 시 null 반환
  src/services/users.service.js
Labels: :bug: Bug

#179 Feat: https 적용
  .gitignore
  src/index.js
Labels: :sparkles: Feat

#155 Feat: #140-get-weekly-verification-api
  prisma/migrations/20250215154348_/migration.sql
  prisma/migrations/20250215155746_/migration.sql
  src/controllers/verification/verification.controller.js
  src/errors/verification/verification.error.js
  src/repositories/verification/verification.repository.js
  src/routes/verification.routes.js
  src/services/verification/verification.service.js
Labels: :sparkles: Feat

#159 Feat: #156-get-challengeCalendar-api
  src/controllers/challenge/participation.controller.js
  src/repositories/challenge/participation.repository.js
  src/routes/challenge.routes.js
  src/services/challenge/participation.service.js
Labels: :sparkles: Feat
